In [1]:
from pathlib import Path

In [2]:
data_dir = Path("/home/rooneyish/Documents/Pulse_SLM/data")
train_file = data_dir / "train.txt"
val_file = data_dir / "val.txt"

In [3]:
train_txt = open(train_file).read()
val_txt = open(val_file).read()

In [4]:
import regex as re

def clean_txt(text):
    # Remove the backslashes escaping the single quotes (\'s -> 's)
    text = re.sub(r"[^\p{Latin}\p{P}\p{N}\p{Z}]", " ", text)
    text = text.replace("\\'", "'")
    
    # Fix the weird spacing around the text formatting
    text = re.sub(r"\s+'\s*([sn])", r"'\1", text)   # fixes ' s or ' n
    text = re.sub(r"={1,}\s*(.*?)\s*={1,}", r"\1", text) # removes headers
    text = re.sub(r"\s+([,.:;?!])", r"\1", text)    # fixes punctuation spacing
    text = re.sub(r"\s*@\s*-\s*@\s*", "-", text)    # fixes @-@ hyphens
    text = re.sub(r"\s+", " ", text).strip()        # collapses extra spaces
    text = text.replace("<unk>", "")
    text = re.sub(r"\n{2,}", "\n", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip()
    text = text.lower()

    
    return text

In [5]:
clean_train_txt = clean_txt(train_txt)
clean_val_txt = clean_txt(val_txt)

In [6]:
len(clean_train_txt), len(clean_val_txt)

(10514596, 1103205)

In [7]:
full_txt = clean_train_txt + clean_val_txt

In [8]:
import nltk.data

nltk.download('punkt')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to /home/rooneyish/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/rooneyish/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [9]:
from nltk.tokenize import sent_tokenize

sent_tokens = sent_tokenize(full_txt)

In [10]:
sent_tokens[:5]

['valkyria chronicles iii senjō no valkyria 3: unrecorded chronicles ( japanese: 3, lit.',
 'valkyria of the battlefield 3 ), commonly referred to as valkyria chronicles iii outside japan, is a tactical role-playing video game developed by sega and media.vision for the playstation portable.',
 'released in january 2011 in japan, it is the third game in the valkyria series.',
 'employing the same fusion of tactical and real-time gameplay as its predecessors, the story runs parallel to the first game and follows the " nameless ", a penal military unit serving the nation of gallia during the second europan war who perform secret black operations and are pitted against the imperial unit " calamaty raven ".',
 'the game began development in 2010, carrying over a large portion of the work done on valkyria chronicles ii.']

In [11]:
sent_w_SE = []
for each in sent_tokens:
    each = ''.join('<S> '+ each + ' <E>')
    sent_w_SE.append(each)

In [12]:
sent_w_SE[:5]

['<S> valkyria chronicles iii senjō no valkyria 3: unrecorded chronicles ( japanese: 3, lit. <E>',
 '<S> valkyria of the battlefield 3 ), commonly referred to as valkyria chronicles iii outside japan, is a tactical role-playing video game developed by sega and media.vision for the playstation portable. <E>',
 '<S> released in january 2011 in japan, it is the third game in the valkyria series. <E>',
 '<S> employing the same fusion of tactical and real-time gameplay as its predecessors, the story runs parallel to the first game and follows the " nameless ", a penal military unit serving the nation of gallia during the second europan war who perform secret black operations and are pitted against the imperial unit " calamaty raven ". <E>',
 '<S> the game began development in 2010, carrying over a large portion of the work done on valkyria chronicles ii. <E>']

In [13]:
sent_w_SE=sent_w_SE[:50]

In [14]:
tokens = []
for sentence in sent_w_SE:
    word = sentence.split()
    tokens.append(word)

In [15]:
len(tokens)

50

In [16]:
corpus = {}
all_tokens = []
for each in tokens:
    for i in range(len(each)):
        all_tokens.append(each[i])

for each in all_tokens:
    if each in corpus:
        corpus[each] += 1
    else:
        corpus[each] = 1

corpus = {k:v for k, v in sorted(corpus.items(), key = lambda item: item[1], reverse = True)}
del corpus['<S>']
del corpus['<E>']
len(corpus)

652

In [17]:
start_token = "<S>"
end_token = "<E>"
start_id = 1
end_id = 2

unique_words = list(corpus.keys())

In [18]:
stoi = {start_token: start_id, end_token: end_id}
itos = {start_id: start_token, end_id: end_token}

In [19]:
for idx, word in enumerate(unique_words):
    target_id = idx + 3
    stoi[word] = target_id
    itos[target_id] = word

In [20]:
len(stoi), len(itos)

(654, 654)

In [21]:
stoi

{'<S>': 1,
 '<E>': 2,
 'the': 3,
 'to': 4,
 'a': 5,
 'and': 6,
 'of': 7,
 'in': 8,
 'are': 9,
 'as': 10,
 'by': 11,
 'with': 12,
 '"': 13,
 'valkyria': 14,
 'is': 15,
 'can': 16,
 'their': 17,
 'character': 18,
 'chronicles': 19,
 'that': 20,
 'game': 21,
 'characters': 22,
 'gallian': 23,
 'it': 24,
 'unit': 25,
 'an': 26,
 'into': 27,
 '",': 28,
 'who': 29,
 'each': 30,
 'army': 31,
 'nameless': 32,
 'military': 33,
 'on': 34,
 'while': 35,
 'also': 36,
 "game's": 37,
 'was': 38,
 'missions': 39,
 'through': 40,
 'be': 41,
 'squad': 42,
 'iii': 43,
 'battlefield': 44,
 'story': 45,
 'during': 46,
 'war': 47,
 'against': 48,
 'such': 49,
 'from': 50,
 'not': 51,
 'they': 52,
 'other': 53,
 'different': 54,
 'at': 55,
 'kurt': 56,
 'move': 57,
 'his': 58,
 'darcsen': 59,
 'japan,': 60,
 'tactical': 61,
 'for': 62,
 'same': 63,
 'gallia': 64,
 'imperial': 65,
 'multiple': 66,
 'both': 67,
 'previous': 68,
 'due': 69,
 'would': 70,
 'take': 71,
 'enemy': 72,
 'player': 73,
 'missions,': 

In [22]:
import torch

In [23]:
tokenized_sentence = [[stoi[token] for token in sentence if token in stoi] for sentence in tokens]

In [24]:
X_data = []
Y_data = []

In [25]:
max(map(len, tokenized_sentence))

78

In [26]:
tokenized_sentence[:2]

[[1, 14, 19, 43, 172, 173, 14, 174, 175, 19, 92, 176, 177, 178, 2],
 [1,
  14,
  7,
  3,
  44,
  179,
  180,
  181,
  93,
  4,
  10,
  14,
  19,
  43,
  94,
  60,
  15,
  5,
  61,
  95,
  96,
  21,
  182,
  11,
  183,
  6,
  97,
  62,
  3,
  98,
  184,
  2]]

In [27]:
sequence = []
for sentence in tokenized_sentence:
    for i in range(1, len(sentence)):
        sequence.append(sentence[:i+1])

In [28]:
sequence[:20]

[[1, 14],
 [1, 14, 19],
 [1, 14, 19, 43],
 [1, 14, 19, 43, 172],
 [1, 14, 19, 43, 172, 173],
 [1, 14, 19, 43, 172, 173, 14],
 [1, 14, 19, 43, 172, 173, 14, 174],
 [1, 14, 19, 43, 172, 173, 14, 174, 175],
 [1, 14, 19, 43, 172, 173, 14, 174, 175, 19],
 [1, 14, 19, 43, 172, 173, 14, 174, 175, 19, 92],
 [1, 14, 19, 43, 172, 173, 14, 174, 175, 19, 92, 176],
 [1, 14, 19, 43, 172, 173, 14, 174, 175, 19, 92, 176, 177],
 [1, 14, 19, 43, 172, 173, 14, 174, 175, 19, 92, 176, 177, 178],
 [1, 14, 19, 43, 172, 173, 14, 174, 175, 19, 92, 176, 177, 178, 2],
 [1, 14],
 [1, 14, 7],
 [1, 14, 7, 3],
 [1, 14, 7, 3, 44],
 [1, 14, 7, 3, 44, 179],
 [1, 14, 7, 3, 44, 179, 180]]

In [29]:
max_len = max(map(len, sequence))
max_len

78

In [30]:
from torch.nn.utils.rnn import pad_sequence
tensor_seq = [torch.tensor(seq) for seq in sequence]
padded_sequence = pad_sequence(tensor_seq, batch_first=True, padding_side='left', padding_value=0)

In [31]:
padded_sequence[100]

tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   1, 188,   3,  63, 189,
          7,  61,   6, 190, 101,  10, 191, 192,   3,  45, 193, 194,   4,   3,
        195,  21,   6, 196,   3,  13,  32,  28,   5, 102,  33,  25, 197,   3,
        198,   7,  64,  46,   3, 103, 104,  47])

In [32]:
len(padded_sequence[100])

78

In [33]:
X = padded_sequence[:, :-1]
y = padded_sequence[:,-1]

In [34]:
X[100]

tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   1, 188,   3,  63, 189,
          7,  61,   6, 190, 101,  10, 191, 192,   3,  45, 193, 194,   4,   3,
        195,  21,   6, 196,   3,  13,  32,  28,   5, 102,  33,  25, 197,   3,
        198,   7,  64,  46,   3, 103, 104])

In [35]:
y[100]

tensor(47)

In [36]:
num_samples = X.shape[0]
num_samples

1383

In [37]:
split_idx_1= int(num_samples * 0.8)
split_idx_2= int(num_samples * 0.9)

In [38]:
X_train, y_train = X[:split_idx_1], y[:split_idx_1]
X_val, y_val = X[split_idx_1:split_idx_2], y[split_idx_1:split_idx_2]
X_test, y_test = X[split_idx_2:], y[split_idx_2:]

In [39]:
len(X_train), len(y_train)

(1106, 1106)

In [40]:
len(X_val), len(y_val)

(138, 138)

In [41]:
len(X_test), len(y_test)

(139, 139)

In [42]:
X_train.shape, y_train.shape, X_val.shape, y_val.shape

(torch.Size([1106, 77]),
 torch.Size([1106]),
 torch.Size([138, 77]),
 torch.Size([138]))

In [43]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")
device

device(type='cuda')

In [44]:
import torch.nn as nn

In [45]:
class Embedding(nn.Module):
    def __init__(self, vocab_size, d_model):
        super().__init__()
        self.vocab_size = vocab_size
        self.d_model = d_model
        self.C = torch.randn((self.vocab_size, self.d_model))
        self.param = nn.Parameter(data=self.C, requires_grad=True)

    def forward(self, x):
        return self.param[x]

In [46]:
len(stoi)

654

In [47]:
model = Embedding(vocab_size=len(stoi), d_model=512).to(device)

In [48]:
bx = X_train[500]
output = model(bx)
output

tensor([[-0.7577,  0.7117, -0.3931,  ...,  1.0184, -1.7500,  0.7719],
        [-0.7577,  0.7117, -0.3931,  ...,  1.0184, -1.7500,  0.7719],
        [-0.7577,  0.7117, -0.3931,  ...,  1.0184, -1.7500,  0.7719],
        ...,
        [-0.0614,  0.2620,  1.1808,  ...,  0.8726, -1.1759, -0.0071],
        [ 0.6680, -0.1426, -0.6154,  ...,  0.4580,  0.0041,  0.4976],
        [ 1.3177, -0.8297, -0.4243,  ...,  1.3598, -0.8551, -0.2047]],
       device='cuda:0', grad_fn=<IndexBackward0>)

In [49]:
output.shape, "for 1 sequence"

(torch.Size([77, 512]), 'for 1 sequence')

In [50]:
import math

In [51]:
class Positional_Embedding(nn.Module):
    def __init__(self, max_len,d_model):
        super().__init__()
        self.max_len = max_len 
        self.d_model = d_model
        pe = torch.zeros(max_len, d_model)

        for pos in range(max_len):
            for i in range(d_model//2):
                denom = 10000**((2*i)/d_model)
                pe[pos, 2*i] = math.sin(pos/denom)
                pe[pos, 2*i+1] = math.cos(pos/denom)

        self.register_buffer('pe', pe)

    def forward(self, x):
        seq_len = x.size(1)
        return x + self.pe[:seq_len, :]    

In [52]:
pos_emb_layer = Positional_Embedding(max_len=output.shape[0], d_model=512).to(device)
pos_emb_layer

Positional_Embedding()

In [53]:
bx_embedded = output.unsqueeze(0)
bx_embedded

tensor([[[-0.7577,  0.7117, -0.3931,  ...,  1.0184, -1.7500,  0.7719],
         [-0.7577,  0.7117, -0.3931,  ...,  1.0184, -1.7500,  0.7719],
         [-0.7577,  0.7117, -0.3931,  ...,  1.0184, -1.7500,  0.7719],
         ...,
         [-0.0614,  0.2620,  1.1808,  ...,  0.8726, -1.1759, -0.0071],
         [ 0.6680, -0.1426, -0.6154,  ...,  0.4580,  0.0041,  0.4976],
         [ 1.3177, -0.8297, -0.4243,  ...,  1.3598, -0.8551, -0.2047]]],
       device='cuda:0', grad_fn=<UnsqueezeBackward0>)

These ☝ are the embeddings before position encoding.

In [54]:
final_output = pos_emb_layer(bx_embedded)

In [55]:
final_output

tensor([[[-0.7577,  1.7117, -0.3931,  ...,  2.0184, -1.7500,  1.7719],
         [ 0.0838,  1.2520,  0.4288,  ...,  2.0184, -1.7499,  1.7719],
         [ 0.1516,  0.2955,  0.5433,  ...,  2.0184, -1.7498,  1.7719],
         ...,
         [-1.0466,  0.4337,  1.9462,  ...,  1.8725, -1.1682,  0.9928],
         [ 0.2802,  0.7791, -0.7083,  ...,  1.4579,  0.0119,  1.4976],
         [ 1.8838, -0.0053, -1.2955,  ...,  2.3597, -0.8472,  0.7952]]],
       device='cuda:0', grad_fn=<AddBackward0>)

These ☝ are the embeddings after position encoding, look at the right side of the tensor block.